server:
  port: 8082
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: ashok-db-service
  datasource:
    url: jdbc:h2:mem:mytestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    initialization-mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

eureka:
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:localhost}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      healthcheck:
        enabled: true

logging:
  level:
    org.springframework: INFO
    com.springboot: DEBUG
    root: info
  pattern:
    console: '%-5level %logger{36} - %msg%n'

  